FROM python:3.12

ENV PYTHONPATH="/code"

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app/ /code/app

WORKDIR /code/app

ENTRYPOINT ["python3", "-m", "streamlit", "run", "./app.py"]

