FROM python:3.12

ENV PYTHONPATH="/code"

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./src/ /code/src
COPY ./tests/ /code/tests
COPY ./entrypoint.sh /code/entrypoint.sh
RUN chmod +x /code/entrypoint.sh

WORKDIR /code

ENTRYPOINT ["./entrypoint.sh"]
