services:
  # =-=-=-=-= POSTGRES =-=-=-=-= 
  # compose from: https://github.com/khezen/compose-postgres/blob/master/docker-compose.yml
  postgres:
    container_name: postgres_container
    image: postgres:14.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: medical_analysis
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  # =-=-=-=-= FastApi =-=-=-=-= 
  fastapi:
    container_name: fastapi
    env_file: 
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile.yaml
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - ./src:/code/src
      - ./tests:/code/tests
      - ./migrations/:/code/migrations
      - ./alembic.ini:/code/alembic.ini

    networks:
      - postgres

    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
