[client]
showSidebarNavigation = false

[browser]
showSidebarNavigation = false

[theme]
primaryColor="#3E497A"
backgroundColor="#e6e7ec"
secondaryBackgroundColor="#ffffff"
textColor="#2e4053"
font = "sans serif"
